### PR TITLE
Removing the status fetching, other elements not needed

### PR DESCRIPTION
**Pull request by maswertyDT**
This code was brought to you by @escheiner who commented out sections of the code that was causing a 502 & 409 error, this will just gather the IPs necessary to run the scan properly. The scanner will skip any status checking of the scan, and it will just run successfully.

### CODE REVIEW

**Review by praymann — COMMENTED** [review]
Nice! 

Looks like a built binary file was added, can we nix that? (might make sense to throw that in `.gitignore` for the future).

**Comment by escheiner** [comment]
> Nice!
> 
> Looks like a built binary file was added, can we nix that? (might make sense to throw that in `.gitignore` for the future).

Are you referring to go.sum and go.mod?

**Comment by maswertyDT** [comment]
@praymann which file are you referring to? I'm unable to find any binaries in this PR, but Im happy to remove it

**Comment by praymann** [comment]
See the following screenshots and links:

image
image

Link to branch and file: https://github.com/Invoca/tenable-scan-launcher/blob/f45afc37388b5a4e51e368df2fe5cc4418cfc942/tenable-scan-launcher

Something of note too, binary files in commits will exist forever in the history even with revert and merge. Someone should rewrite the commits and remove that file then `git push --force-with-lease`.

**Comment by maswertyDT** [comment]
@praymann I appreciate you walking through that, the binary should be deleted and I"ll for sure note that for any future PRs. Thanks!

**Comment by praymann** [comment]
My comments over in #17 still apply here, minus the one about the binary file.

Looks like a `go mod vendor` is needed with the dependency change. (it's coming from the Slack functionality, [here](https://github.com/invoca/tenable-scan-launcher/blob/master/pkg/slack/slack.go#L17), not sure why it wasn't vendored before). Read https://go.dev/ref/mod#vendoring if you're wondering how it works.

You can replicate the failing test with `go test ./...`.

**Comment by praymann** [comment]
This duplicates https://github.com/Invoca/tenable-scan-launcher/pull/18, closing.

**Pull request closed without merging**
